name: Trivy Security Scan

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:

  filesystem-scan:
    name: Dependency & Misconfiguration Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL

  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          format: table

  docker-image-scan:
    name: Docker Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t securepass:latest .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: securepass:latest
          format: table
          severity: HIGH,CRITICAL